name: cat_gallery
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cached_network_image: ^2.3.2+1

  localstorage: ^3.0.0

  shimmer: ^1.1.1
  
  flutter_dotenv: ^2.1.0
  
  provider: ^4.3.2+2
  
  flutter:
    sdk: flutter
  
  http: ^0.12.2

  flutter_svg: ^0.19.0

  share: ^0.6.5+2

  cupertino_icons: ^0.1.3



dev_dependencies:
  flutter_test:
    sdk: flutter
   
  flutter_launcher_icons: ^0.7.2
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/favicon.png"

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: ArchitectsDaughter
      fonts:
        - asset: fonts/ArchitectsDaughter-Regular.ttf
