name: cat_gallery
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cached_network_image: ^2.3.2+1

  flutter_dotenv: ^2.1.0
  
  provider: ^4.3.2+2
  
  flutter:
    sdk: flutter
  
  http: ^0.12.2

  flutter_svg: ^0.19.0

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - images/cat-1.jpg
    - images/cat-2.jpg
    - images/cat-3.jpg
    - images/logo.svg


  fonts:
    - family: ArchitectsDaughter
      fonts:
        - asset: fonts/ArchitectsDaughter-Regular.ttf
